version: '3'

networks:
  mynetwork:
    driver: bridge

services:
  infinispan-server-lon:
    image: infinispan/server:15.2
    environment:
      - USER=admin
      - PASS=secret
      - SERVER_LIBS=org.postgresql:postgresql:42.7.3
    ports:
      - "11222:11222"
    container_name: infinispan-lon
    networks:
      - mynetwork
    depends_on:
      - database
    command: -c infinispan-xsite.xml -Dinfinispan.site.name=LON -Djgroups.mcast_port=46656
  infinispan-server-nyc:
      image: infinispan/server:15.2
      environment:
        - USER=admin
        - PASS=secret
      ports:
        - "31222:11222"
      container_name: infinispan-nyc
      networks:
        - mynetwork
      command: -c infinispan-xsite.xml -Dinfinispan.site.name=NYC -Djgroups.mcast_port=46657
  database:
    image: postgres:17
    environment:
      POSTGRES_USER: "infinispan"
      POSTGRES_PASSWORD: "secret"
      POSTGRES_DB: "retailstore"
    ports:
      - "5432:5432"
    networks:
      - mynetwork