apiVersion: infinispan.org/v1
kind: Infinispan
metadata:
  name: infinispan
  namespace: david-test
spec:
  expose:
    type: LoadBalancer
  replicas: 1
  security:
    endpointSecretName: connect-secret
    endpointEncryption:
      type: None
  dependencies:
    artifacts:
    - maven: org.postgresql:postgresql:42.7.3